### ISSUE TITLE
Is there a way I could make the response with high lighted color?

### ISSUE THREAD

**Issue by YangRongAtGit** [wraith13/wandbox-vscode#10]
Hello,

The MS code project is great, thanks for your great work. I just wondering that possible in the output from the wandbox server. I may get the result in different color in the output console? For now, all texts a white. It is a bit difficult to read if there are a lot of text in output.

Thanks,

Rong

**Comment by wraith13** [comment]
Oh, I think so too. But it seems there is no way to do it well.

First, OutputChannel dose not support color specification.
https://code.visualstudio.com/docs/extensionAPI/vscode-api#OutputChannel

It is not impossible to color it as this extension does. But it is not a suitable way for this case.
https://marketplace.visualstudio.com/items?itemName=IBM.output-colorizer

**Comment by YangRongAtGit** [comment]
Thansk for your response. Wish the future vscode provides interfaces for doing it. :)

**Comment by YangRongAtGit** [comment]
hello 道化,


Just wondering that, is it possible that I could open a shared URL in VS code? e.g, I edited code in office machine. After back home, I will work on another machine. Could I open the shared link in the VS code installed on the home machine?


Or


I can only copy the code from the shared URL into the VSCode. In that case, if I would like to share again, the code will be uploaded to a new URL, right?


Thanks


r0nG

Auckland, New Zealand


________________________________
发件人: 道化 <notifications@github.com>
发送时间: 2017年6月29日 16:14
收件人: wraith13/wandbox-vscode
抄送: r0nG; Author
主题: Re: [wraith13/wandbox-vscode] Is there a way I could make the response with high lighted color? (#10)


Oh, I think so too. But it seems there is no way to do it well.

First, OutputChannel dose not support color specification.
https://code.visualstudio.com/docs/extensionAPI/vscode-api#OutputChannel

Visual Studio Code API Reference<https://code.visualstudio.com/docs/extensionAPI/vscode-api#OutputChannel>
code.visualstudio.com
Visual Studio Code extensions (plug-ins) API Reference.



It is not impossible to color it as this extension does. But it is not a suitable way for this case.
https://marketplace.visualstudio.com/items?itemName=IBM.output-colorizer

[https://ibm.gallerycdn.vsassets.io/extensions/ibm/output-colorizer/0.1.1/1493650186969/Microsoft.VisualStudio.Services.Icons.Default]<https://marketplace.visualstudio.com/items?itemName=IBM.output-colorizer>

Output Colorizer - Visual Studio Marketplace<https://marketplace.visualstudio.com/items?itemName=IBM.output-colorizer>
marketplace.visualstudio.com
Extension for Visual Studio Code - Syntax highlighting for log files



―

**Comment by wraith13** [comment]
>I can only copy the code from the shared URL into the VSCode. In that case, if I would like to share again, the code will be uploaded to a new URL, right?

I'm sorry but this one.

**Comment by YangRongAtGit** [comment]
Thanks for your help, wish you have a nice day


😊

r0nG

Auckland, New Zealand


________________________________
发件人: 道化師 <notifications@github.com>
发送时间: 2017年6月30日 1:24
收件人: wraith13/wandbox-vscode
抄送: r0nG; State change
主题: Re: [wraith13/wandbox-vscode] Is there a way I could make the response with high lighted color? (#10)


I can only copy the code from the shared URL into the VSCode. In that case, if I would like to share again, the code will be uploaded to a new URL, right?

I'm sorry but this one.
