### ISSUE TITLE
Could I post mutli files by wandbox-vscode to wangbox.org ?

### ISSUE THREAD

**Issue by S1xe** [wraith13/wandbox-vscode#12]
Here,I had two files `Hello.hpp` and `main.cpp` that I wanted to post to wangbox.org.
The contents of the two files are as follows.
#### Hello.cpp
```C++
#ifndef HELLO_HPP
#define HELLO_HPP

int fun() {
    return 0;
}
#endif
```

#### Hello.cpp
```c++
#include <iostream>
#include "Hello.hpp"
int main() {
    std::cout << fun() << std::endl;
    return 0;
}
```

Then , I added `Hello.hpp` in `Wandbox:Set Option` - `Select a add file`.
It returned message as follows.
```
🐾 Bow-wow! Fri Oct 13 2017 09:12:47 GMT+0800 (中国标准时间)
Set codes "d:\zbl\cpp\Hello.hpp" for "d:\zbl\cpp\main.cpp"
```

Then,I clicked `Wandbox:Run`.
It returned message as follows.
```
🐾 Bow-wow! Fri Oct 13 2017 09:15:39 GMT+0800 (中国标准时间)
HTTP POST https://wandbox.org/api/compile.json
{
    "compiler": "gcc-head",
    "code": "d:\\zbl\\cpp\\main.cpp",
    "codes": "d:\\zbl\\cpp\\Hello.hpp",
    "options": "warning,boost-1.65.1-gcc-head,gnu++1z,cpp-no-pedantic"
}
HTTP statusCode: 200
status: 1
🚫 compiler_error: 
prog.cc:2:10: fatal error: Hello.hpp: No such file or directory
 #include "Hello.hpp"
          ^~~~~~~~~~~
compilation terminated.
```
It seemed the `Hello.hpp` was useless.
How can I post mutli files ? Or, I made some mistakes in those operation process.

**Comment by S1xe** [comment]
Maybe,I found the reason why it showed `Hello.hpp: No such file or directory` before.
The files'name had been changed! It should be `Hello.hpp` , but now  was `d:\zbl\cpp\Hello.hpp`.
https://wandbox.org/permlink/Y1Q6elAR7hfStMuD

**Comment by wraith13** [comment]
Perhaps I have only tested multiple files with untitled documents.
This is probably a bug.

**Comment by S1xe** [comment]
Maybe users can customize files'name while they post files.

**Comment by S1xe** [comment]
Or,more files can be added in "code".
