### ISSUE TITLE
Settings menu disappears instantly after entering

### ISSUE THREAD

**Issue by KrzaQ** [wraith13/wandbox-vscode#15]
After updating VS Code to 1.43.0 I am unable to set wandbox options: [video](https://misc.krzaq.cc/temp/2020-03-18_16-21-03.mp4)

I am getting the same thing when trying to set compiler and set wandbox options.

The log shows as follows:
```
🐾 Bow-wow! Wed Mar 18 2020 16:19:22 GMT+0100 (Central European Standard Time)
Canceled

🐾 Bow-wow! Wed Mar 18 2020 16:20:58 GMT+0100 (Central European Standard Time)
Canceled

🐾 Bow-wow! Wed Mar 18 2020 16:21:01 GMT+0100 (Central European Standard Time)
Canceled
```

Wandbox Run works correctly, but I am locked into specific compiler and version.

**Comment by KrzaQ** [comment]
Update: after restarting, the first try to open settings does work. Any further does not.
```
🐾 Bow-wow! Wed Mar 18 2020 16:34:06 GMT+0100 (Central European Standard Time)
HTTP GET https://wandbox.org/api/list.json?from=wandbox-vscode
statusCode: 200
Set codes "/home/krzaq/code/cpptest/all.hpp" for "/home/krzaq/code/cpptest/wb.cpp"

🐾 Bow-wow! Wed Mar 18 2020 16:34:29 GMT+0100 (Central European Standard Time)
Canceled
```

**Comment by KrzaQ** [comment]
Downgrading to 1.42.1 does indeed fix this. I'll stay with 1.42.1 until this is resolved.

**Comment by wraith13** [comment]
I apologize for the inconvenience. I will solve this problem in a few days.

**Comment by KrzaQ** [comment]
No need to apologize! Thank you for providing this plugin, it's very useful.

**Comment by wraith13** [comment]
I've released a new version of this extension that fixes this problem. Please reopen this issue if the problem still reproduces.
